// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit level for Design mode. Determines how rigorously assumptions are verified.
 */
export type DesignAuditLevel = "basic" | "standard" | "deep";
