// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated: retained only for deserializing legacy history/config.
 * Use `ody_web_search::WebSearchConfig` for new configuration.
 */
export type WebSearchLocation = { country: string | null, region: string | null, city: string | null, timezone: string | null, };
