//! Canvas 注入（工程模式 Canvas 提案 §12 切片 2/3，odyBox 侧契约见
//! docs/product/project-canvas-proposal.md）。
//!
//! Vite 工程的 dev server 启动时，把两个 Vite 插件 + 一个包装 config
//! 生成到 `<root>/node_modules/.ody/`（node_modules 是生成物，写这里
//! 不算改用户文件，且插件文件在 node_modules 内才能解析到工程自己的
//! @babel/core），然后把 `--config node_modules/.ody/ody.canvas.config.mjs`
//! 追加到 dev 命令。包装 config 加载用户原 vite config（vite 的
//! loadConfigFromFile 可处理 .ts）并 merge 两个 ody 插件：
//!
//! - `ody-canvas-id`（切片 2）：babel 注入确定性 `data-ody-id`，manifest
//!   写 `<root>/.ody/canvas-id-map.json`（§12.1 格式）。
//! - `ody-canvas-bridge`（切片 3）：transformIndexHtml 注入与 odyBox
//!   Artifact 场景协议逐字一致的 bridge 脚本。
//!
//! 任何失败一律降级为不注入（渲染可用、点选降级），绝不让 dev server
//! 起不来（提案 §6 分期承诺）。

use std::fs;
use std::path::{Path, PathBuf};

const ODY_ID_PLUGIN_JS: &str = include_str!("../assets/canvas/ody-id-plugin.mjs");
const ODY_BRIDGE_PLUGIN_JS: &str = include_str!("../assets/canvas/ody-bridge-plugin.mjs");

/// 生成目录在 node_modules 内（生成物，非用户文件）。
fn ody_dir(root: &Path) -> PathBuf {
    root.join("node_modules").join(".ody")
}

/// 相对 service cwd（= root）的包装 config 路径。
pub(crate) fn canvas_config_rel_path() -> PathBuf {
    Path::new("node_modules")
        .join(".ody")
        .join("ody.canvas.config.mjs")
}

/// 注入门槛：Vite 工程 + dev script 命令本身跑 vite（防止
/// "dev": "node server.js" 这类同工程异脚本的工程被误注入）。
pub(crate) fn canvas_injectable(tech_ids: &[String], script_command: &str) -> bool {
    let is_vite = tech_ids.iter().any(|id| id.eq_ignore_ascii_case("vite"));
    is_vite && script_command.to_ascii_lowercase().contains("vite")
}

/// 生成/刷新注入资产，返回追加到 dev 命令的额外参数（`--config <相对路径>`）。
/// 门槛不满足返回 None；写入失败也返回 None（降级不注入）。
pub(crate) fn prepare_canvas_inject(
    root: &Path,
    tech_ids: &[String],
    script_command: &str,
) -> Option<Vec<String>> {
    if !canvas_injectable(tech_ids, script_command) {
        return None;
    }
    let dir = ody_dir(root);
    fs::create_dir_all(&dir).ok()?;
    fs::write(dir.join("ody-id-plugin.mjs"), ODY_ID_PLUGIN_JS).ok()?;
    fs::write(dir.join("ody-bridge-plugin.mjs"), ODY_BRIDGE_PLUGIN_JS).ok()?;
    fs::write(
        dir.join("ody.canvas.config.mjs"),
        render_wrapper_config(root),
    )
    .ok()?;
    Some(vec![
        "--config".to_owned(),
        canvas_config_rel_path().to_string_lossy().into_owned(),
    ])
}

/// 包装 vite config：加载用户原配置（若存在）并 merge 两个 ody 插件。
/// 用户配置候选按 Vite 默认解析顺序；loadConfigFromFile 内部用 esbuild
/// 打包，.ts/.mts 均可；加载失败降级为空配置（插件仍注入，用户配置的
/// 丢失只影响该 dev 会话的自定义项，不影响可服务性）。
fn render_wrapper_config(root: &Path) -> String {
    let root_json =
        serde_json::to_string(&root.to_string_lossy()).unwrap_or_else(|_| "\".\"".to_owned());
    format!(
        r#"// GENERATED by ody-app-server (canvas inject, proposal §12 slice 2/3).
// 每次 dev server 启动时重新生成；不要手工编辑。
// 用户工程文件零改动：本文件通过 --config 注入，用户原 vite config 被
// loadConfigFromFile 加载后 merge。
import {{ defineConfig, mergeConfig, loadConfigFromFile }} from 'vite'
import odyId from './ody-id-plugin.mjs'
import odyBridge from './ody-bridge-plugin.mjs'
import {{ existsSync }} from 'node:fs'

const root = {root_json}
const USER_CONFIG_CANDIDATES = [
  'vite.config.ts',
  'vite.config.mts',
  'vite.config.cts',
  'vite.config.js',
  'vite.config.mjs',
  'vite.config.cjs',
]

async function loadUserConfig() {{
  for (const name of USER_CONFIG_CANDIDATES) {{
    if (!existsSync(`${{root}}/${{name}}`)) continue
    try {{
      const loaded = await loadConfigFromFile({{ command: 'serve', mode: 'development' }}, `${{root}}/${{name}}`, root)
      return loaded?.config ?? {{}}
    }} catch {{
      return {{}} // 用户配置加载失败：降级为空配置，ody 插件仍生效
    }}
  }}
  return {{}}
}}

const userConfig = await loadUserConfig()
export default mergeConfig(userConfig, {{ plugins: [odyId({{ root }}), odyBridge()] }})
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tech(ids: &[&str]) -> Vec<String> {
        ids.iter().map(|id| (*id).to_owned()).collect()
    }

    #[test]
    fn injectable_requires_vite_tech_and_vite_command() {
        assert!(canvas_injectable(&tech(&["vite"]), "vite"));
        assert!(canvas_injectable(&tech(&["react", "vite"]), "vite --host"));
        assert!(!canvas_injectable(&tech(&["react"]), "vite"));
        assert!(!canvas_injectable(&tech(&["vite"]), "node server.js"));
        assert!(!canvas_injectable(&tech(&["webpack"]), "webpack serve"));
        assert!(canvas_injectable(&tech(&["Vite"]), "VITE"));
    }

    #[test]
    fn prepare_writes_assets_under_node_modules_and_returns_config_args() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        let args = prepare_canvas_inject(root, &tech(&["vite"]), "vite").expect("inject args");

        let ody = root.join("node_modules").join(".ody");
        assert!(ody.join("ody-id-plugin.mjs").exists());
        assert!(ody.join("ody-bridge-plugin.mjs").exists());
        assert!(ody.join("ody.canvas.config.mjs").exists());

        assert_eq!(
            args,
            vec![
                "--config".to_owned(),
                "node_modules/.ody/ody.canvas.config.mjs".to_owned()
            ]
        );
    }

    #[test]
    fn prepare_is_idempotent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        let first = prepare_canvas_inject(root, &tech(&["vite"]), "vite");
        let second = prepare_canvas_inject(root, &tech(&["vite"]), "vite");
        assert_eq!(first, second);
        // 第二次生成后资产仍在
        assert!(
            root.join("node_modules/.ody/ody.canvas.config.mjs")
                .exists()
        );
    }

    #[test]
    fn prepare_returns_none_and_writes_nothing_when_not_injectable() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        let result = prepare_canvas_inject(root, &tech(&["webpack"]), "webpack serve");
        assert!(result.is_none());
        assert!(!root.join("node_modules/.ody").exists());
    }

    #[test]
    fn wrapper_references_root_as_json_and_loads_user_config_candidates() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        prepare_canvas_inject(root, &tech(&["vite"]), "vite").expect("inject args");
        let wrapper = fs::read_to_string(root.join("node_modules/.ody/ody.canvas.config.mjs"))
            .expect("read wrapper");

        let root_json = serde_json::to_string(&root.to_string_lossy()).unwrap();
        assert!(wrapper.contains(&format!("const root = {root_json}")));
        assert!(wrapper.contains("loadConfigFromFile"));
        assert!(wrapper.contains("'vite.config.ts'"));
        assert!(wrapper.contains("mergeConfig(userConfig"));
        assert!(wrapper.contains("odyId({ root })"));
        assert!(wrapper.contains("odyBridge()"));
        // 不能 import 用户配置文件本身（.ts 无法被 node 直接 import）
        assert!(!wrapper.contains("await import("));
    }

    #[test]
    fn embedded_assets_are_nonempty_and_export_default_factory() {
        assert!(ODY_ID_PLUGIN_JS.contains("export default function odyCanvasIdPlugin"));
        assert!(ODY_ID_PLUGIN_JS.contains("data-ody-id"));
        assert!(ODY_ID_PLUGIN_JS.contains("canvas-id-map.json"));
        assert!(ODY_BRIDGE_PLUGIN_JS.contains("export default function odyCanvasBridgePlugin"));
        assert!(ODY_BRIDGE_PLUGIN_JS.contains("transformIndexHtml"));
        assert!(ODY_BRIDGE_PLUGIN_JS.contains("odybox-canvas-preview"));
    }
}
