// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthState } from "./AuthState";

export type GetAuthStateResponse = { authState: AuthState | null, };
