// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountParams = {
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * This flag is no longer used; API key auth does not require a refresh flow.
 */
refreshToken?: boolean, };
