// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageDailyBucket } from "./TokenUsageDailyBucket";
import type { TokenUsageSummary } from "./TokenUsageSummary";

export type GetTokenUsageResponse = { summary: TokenUsageSummary, dailyUsageBuckets: Array<TokenUsageDailyBucket> | null, };
