// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanModeLogKind } from "./PlanModeLogKind";

/**
 * Structured planning log delta for Plan/Design mode. Emitted to surface
 * rigor reminders, split checks, completeness gates, and mode transitions.
 */
export type PlanModeLogDeltaNotification = { threadId: string, turnId: string, eventId: string, occurredAtMs: bigint, kind: PlanModeLogKind, message: string, detail: string | null, };
