// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillsDeleteParams = {
/**
 * Name of the installed skill to remove (the directory name under `$ODY_HOME/skills`).
 */
name: string, };
