// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirror of `ody_core_skills::model::SkillType` for the wire protocol.
 * Serialized as the SKILL.md frontmatter `type:` value.
 */
export type SkillType = "prompt" | "inline" | "flow" | "knowledge";
