// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillsUpgradeParams = {
/**
 * Name of the installed skill to upgrade (the directory name under `$ODY_HOME/skills`).
 */
name: string,
/**
 * GitHub source URL. Falls back to the `source.json` recorded at install
 * time when omitted; the request fails when neither is available.
 */
source?: string | null,
/**
 * Optional path inside the repository that holds the SKILL.md.
 */
path?: string | null, };
