// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillsMarketplaceInstallParams = {
/**
 * GitHub source URL of the skill repository.
 */
source: string,
/**
 * Optional expected skill name; falls back to the repo directory name.
 */
name?: string | null,
/**
 * Optional path inside the repository that holds the SKILL.md.
 */
path?: string | null, };
