// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualStyleDeclaration } from "./VisualStyleDeclaration";

export type VisualPatchOperation = { "type": "setStyle", element_id: string, declarations: Array<VisualStyleDeclaration>, };
