// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualPatchSet } from "./VisualPatchSet";
import type { VisualRevisionReason } from "./VisualRevisionReason";

export type VisualArtifact = { id: string, projectId: string, lineageId: string, revision: number, parentArtifactId: string | null, name: string,
/**
 * Complete standalone source. The runtime applies deterministic patches to this value.
 */
html: string, revisionReason: VisualRevisionReason, patchSet: VisualPatchSet | null, createdAtMs: number, updatedAtMs: number, };
