// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualPatchOperation } from "./VisualPatchOperation";

export type VisualPatchSet = { id: string, baseArtifactId: string, resultArtifactId: string, operations: Array<VisualPatchOperation>, createdAtMs: number, };
