// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualViewport } from "./VisualViewport";

export type VisualSnapshot = { id: string, projectId: string, artifactId: string, viewport: VisualViewport, width: number, height: number,
/**
 * PNG bytes encoded by the capture-capable client/browser.
 */
dataBase64: string, createdAtMs: number, };
