// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated: retained for loading old thread history.
 */
export type WebSearchAction = { "type": "search", query: string | null, queries: Array<string> | null, result_count?: number, } | { "type": "openPage", url: string | null, } | { "type": "findInPage", url: string | null, pattern: string | null, } | { "type": "other" };
