// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRootRole } from "./WorkspaceRootRole";

export type WorkspaceRoot = {
/**
 * Canonicalized absolute path on the local filesystem.
 */
path: string,
/**
 * Derived from bind order: `roots[0]` is the primary (default cwd) root.
 */
role: WorkspaceRootRole,
/**
 * Authorization provenance. E0 only supports `user_selected`.
 */
authSource: string, };
