// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceGitDiff = { repoRoot: string | null,
/**
 * False when the git binary is unavailable, errors, or times out.
 */
available: boolean, error: string | null,
/**
 * `git diff HEAD` output. Untracked files are not included (v1
 * limitation; per-changeset diffs cover them).
 */
unifiedDiff: string | null, };
