// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceValidationKind } from "./WorkspaceValidationKind";
import type { WorkspaceValidationStatus } from "./WorkspaceValidationStatus";

export type WorkspaceValidationRun = { kind: WorkspaceValidationKind, script: string, status: WorkspaceValidationStatus, exitCode: number | null,
/**
 * Trailing stdout bytes, capped at 64 KiB.
 */
stdoutTail: string,
/**
 * Trailing stderr bytes, capped at 64 KiB.
 */
stderrTail: string, startedAtMs: number, durationMs: number, };
