// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceChangeSetCommitOutcome } from "./WorkspaceChangeSetCommitOutcome";

/**
 * Git commit outcome for one project root after changeset apply.
 */
export type WorkspaceChangeSetCommitReport = { rootPath: string, outcome: WorkspaceChangeSetCommitOutcome, };
