// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceGitStatus = {
/**
 * True when a `.git` entry is found at or above the root (pure fs probe,
 * no git binary required).
 */
isRepo: boolean, repoRoot: string | null, branch: string | null, headCommitHash: string | null, hasChanges: boolean | null,
/**
 * False when the git binary is unavailable, errors, or times out; `error`
 * carries the diagnosable reason and the rest of the scan is unaffected.
 */
available: boolean, error: string | null, };
