// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceObservedNetworkFailure } from "./WorkspaceObservedNetworkFailure";
import type { WorkspaceServiceHealth } from "./WorkspaceServiceHealth";
import type { WorkspaceServiceRef } from "./WorkspaceServiceRef";
import type { WorkspaceSourceRef } from "./WorkspaceSourceRef";

export type WorkspaceNetworkDiagnosis = {
/**
 * The failure this diagnosis answers (echoed).
 */
failure: WorkspaceObservedNetworkFailure,
/**
 * Project service matched by loopback port: preferred non-terminal,
 * else the most recent terminal record — a crashed backend is
 * exactly what diagnosis must surface.
 */
matchedService?: WorkspaceServiceRef,
/**
 * On-demand health probe of the matched service.
 */
health?: WorkspaceServiceHealth, stdoutTail?: string, stderrTail?: string,
/**
 * Log lines mentioning any path segment of the failure URL.
 */
logExcerpt?: string,
/**
 * Source candidates: route entries matching the path (and its
 * prefix-stripped variants) plus file-name matches on the last
 * path segment, from the on-demand workspace source index.
 */
sourceCandidates: Array<WorkspaceSourceRef>,
/**
 * Human-readable correlation notes (non-loopback URL, no service
 * match, index truncation, ...).
 */
notes?: Array<string>, };
