// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceServiceHealth } from "./WorkspaceServiceHealth";
import type { WorkspaceServiceStatus } from "./WorkspaceServiceStatus";

export type WorkspaceServiceRef = { id: string, projectId: string, name: string,
/**
 * Index into the bound project's `roots`; cwd of the dev server.
 */
rootIndex: number,
/**
 * package.json script name chosen by the client from the E0 scan.
 */
script: string,
/**
 * Fully resolved command line actually spawned (`<pm> run <script> -- ...`).
 */
command: string, port: number,
/**
 * Loopback URL of the managed dev server.
 */
url: string, status: WorkspaceServiceStatus, pid: number, exitCode: number,
/**
 * Last on-demand health probe result (`list` only; never mutates status).
 */
health: WorkspaceServiceHealth | null,
/**
 * Diagnosable terminal reason (startup failure, restart normalization).
 */
error: string | null, createdAtMs: number, updatedAtMs: number, };
