// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceTreeEntryKind } from "./WorkspaceTreeEntryKind";

export type WorkspaceTreeEntry = {
/**
 * File name within the parent directory.
 */
name: string,
/**
 * Root-relative `/`-separated path of the entry.
 */
path: string, kind: WorkspaceTreeEntryKind, };
