// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceServiceHealthCheck } from "./WorkspaceServiceHealthCheck";

/**
 * Declarative, project-scoped service definition (E3). Single-root
 * monorepo sub-packages use `cwd`; dual-root projects use per-spec
 * `rootIndex`. Source authority stays in the user's directories.
 */
export type WorkspaceServiceSpec = {
/**
 * Server-generated `spec-{uuid}`.
 */
id: string, projectId: string,
/**
 * Unique among the project's specs; 1-64 chars.
 */
name: string,
/**
 * Index into the bound project's `roots`.
 */
rootIndex: number,
/**
 * package.json script name from the E0 scan; the Runtime never guesses.
 */
script: string,
/**
 * Requested port; occupied -> structured error at start time. Omitted
 * -> framework default probed, then a free port auto-selected.
 */
port?: number,
/**
 * Root-relative working directory for the service process. Normalized
 * and escape-checked at define time; the resolved cwd never leaves
 * the bound root.
 */
cwd?: string | null,
/**
 * Names of other specs in the same project that must be Ready (and
 * healthy when they define a health check) before this one starts.
 */
dependsOn?: Array<string>, healthCheck?: WorkspaceServiceHealthCheck | null,
/**
 * Readiness deadline per service; default 60s, clamp [5s, 300s].
 */
readyTimeoutMs?: number, createdAtMs: number, updatedAtMs: number, };
