// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSourceRange } from "./WorkspaceSourceRange";

export type WorkspaceSourceRef = { artifactId: string,
/**
 * Canonicalized owning root path from the binding record.
 */
rootPath: string,
/**
 * Path relative to the owning root, `/`-separated.
 */
filePath: string,
/**
 * 1-based inclusive line range of the symbol block; None = whole file.
 */
range: WorkspaceSourceRange | null,
/**
 * Export symbol name; file stem when no export is found.
 */
symbol: string, routePath: string | null,
/**
 * sha256 hex of the ranged content (whole file when range is None).
 */
contentHash: string,
/**
 * sha256 hex of the whole file.
 */
fileHash: string, };
