// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceServiceChangedReason } from "./WorkspaceServiceChangedReason";
import type { WorkspaceServiceRef } from "./WorkspaceServiceRef";

/**
 * Broadcast service lifecycle change (E4: replaces client polling).
 */
export type WorkspaceServiceChangedNotification = { projectId: string, reason: WorkspaceServiceChangedReason,
/**
 * Affected services after the state transition.
 */
services: Array<WorkspaceServiceRef>, };
