// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRoot } from "./WorkspaceRoot";

export type WorkspaceProjectRef = { id: string, name: string, schemaVersion: number, roots: Array<WorkspaceRoot>, createdAtMs: number, updatedAtMs: number, };
