// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A network failure observed by the caller's browser (renderer preview
 * surface or agent tool result). E3 diagnose correlates these against
 * managed services, their logs, and the workspace source index; the
 * Runtime never opens a browser itself (narrow-protocol decision).
 */
export type WorkspaceObservedNetworkFailure = {
/**
 * Full request URL as observed.
 */
url: string, method?: string, status?: number,
/**
 * Browser-level error text (e.g. "net::ERR_CONNECTION_REFUSED").
 */
error?: string, occurredAtMs?: number, };
