// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * One append-only audit record. `detail` is a whitelist-built summary:
 * paths, names, counts, ids, hashes — never file content, never env/secret
 * values (strategy 8.2 key discipline).
 */
export type WorkspaceAuditEvent = { seq: number, timestampMs: number, projectId: string | null,
/**
 * Dotted operation id, e.g. "changeset.apply", "service.startAll".
 */
operation: string,
/**
 * "ok" | "error".
 */
outcome: string,
/**
 * Whitelisted structured summary (object), e.g. {"changesetId":"cs-1",
 * "files":["0:src/a.ts"]} or {"error":"baseHash mismatch"}.
 */
detail: JsonValue, };
