// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSourceArtifact } from "./WorkspaceSourceArtifact";
import type { WorkspaceSourceRef } from "./WorkspaceSourceRef";

export type WorkspaceSourceIndex = { projectId: string,
/**
 * Artifacts and refs are parallel 1:1 vectors.
 */
artifacts: Array<WorkspaceSourceArtifact>, refs: Array<WorkspaceSourceRef>, indexedAtMs: number, truncated: boolean,
/**
 * Per-root diagnosable problems; remaining roots still index.
 */
errors: Array<string>, };
