// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceFileEventKind } from "./WorkspaceFileEventKind";

/**
 * One debounced external file change under a project root.
 */
export type WorkspaceFileEvent = { rootIndex: number,
/**
 * Root-relative `/`-joined path.
 */
path: string, kind: WorkspaceFileEventKind,
/**
 * sha256 of the file content after the change; None for removals or
 * unreadable/racing reads (best-effort, never blocks notification).
 */
contentHash: string | null, };
