// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceValidationOverall } from "./WorkspaceValidationOverall";
import type { WorkspaceValidationRun } from "./WorkspaceValidationRun";

export type WorkspaceValidationReport = { runs: Array<WorkspaceValidationRun>, overall: WorkspaceValidationOverall, };
