// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a managed dev server. Terminal: Failed, Exited,
 * Stopped. Runtime restart normalizes lingering Starting/Ready to Stopped.
 */
export type WorkspaceServiceStatus = "starting" | "ready" | "failed" | "exited" | "stopped";
