// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSourceKind } from "./WorkspaceSourceKind";

export type WorkspaceSourceEntry = { kind: WorkspaceSourceKind,
/**
 * File stem (no extension).
 */
name: string,
/**
 * Path relative to the scanned root, `/`-separated.
 */
path: string,
/**
 * Route path when `kind` is `Route`, derived from directory conventions.
 */
routePath: string | null, };
