// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceArtifactBridgeStatus } from "./WorkspaceArtifactBridgeStatus";

/**
 * Provenance record for importing a Visual Artifact's standalone source
 * into a bound workspace root. The import itself always lands as a Pending
 * changeset (single Add change), so it flows through the normal review and
 * conflict-detection machinery; this record tracks artifact lineage so the
 * "prototype merged into a real workspace" ratio (§10.2) is computable
 * runtime-side.
 */
export type WorkspaceArtifactBridge = {
/**
 * Server-generated `ab-{uuid}`.
 */
id: string, projectId: string,
/**
 * Provenance: the Visual Artifact id being imported, when known.
 */
artifactId: string | null,
/**
 * Root-relative `/`-separated target file the artifact source lands in.
 */
targetPath: string,
/**
 * The Pending changeset carrying the import; status mirrors its lifecycle.
 */
changesetId: string,
/**
 * Client-generated key makes bridge retries idempotent.
 */
idempotencyKey: string, status: WorkspaceArtifactBridgeStatus, createdAtMs: number, updatedAtMs: number, };
