// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSourceKind } from "./WorkspaceSourceKind";

export type WorkspaceSourceArtifact = {
/**
 * Stable id: "{kind}:{root_index}:{path}".
 */
id: string, kind: WorkspaceSourceKind, name: string,
/**
 * Path relative to the owning root, `/`-separated.
 */
path: string, routePath: string | null,
/**
 * Framework signal id from discovery, e.g. "react", "vue", "next".
 */
framework: string | null, };
