// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health check definition attached to a service spec (E3): probed on the
 * service's loopback origin and used as the orchestration gate between
 * dependency levels.
 */
export type WorkspaceServiceHealthCheck = {
/**
 * HTTP path probed on the service's loopback origin, e.g. "/api/health".
 */
path: string,
/**
 * Exact expected status; default 200. Stricter than the `list`
 * probe's 2xx tolerance — a degraded 500 must fail the gate.
 */
expectStatus?: number,
/**
 * Per-attempt timeout; default 2000 ms, clamped to [200, 10000].
 */
timeoutMs?: number, };
