// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceFileChangeKind } from "./WorkspaceFileChangeKind";

export type WorkspaceFileChange = {
/**
 * Index into the project binding's `roots` vector.
 */
rootIndex: number,
/**
 * Root-relative `/`-separated path; normalized and escape-checked at
 * create. The resolved absolute target is stored server-side.
 */
path: string, kind: WorkspaceFileChangeKind,
/**
 * sha256 hex the change expects on disk. Required for Update/Delete.
 */
baseHash: string | null,
/**
 * Full new file content. Required for Add/Update.
 */
content: string | null, };
