// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceTechEntry = {
/**
 * Framework or tool signal id, e.g. "react", "vite", "next", "vue",
 * "svelte", "angular", "express".
 */
id: string,
/**
 * Raw dependency declaration version when discovered from package.json.
 */
version: string | null, };
