// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRootDiscovery } from "./WorkspaceRootDiscovery";

export type WorkspaceDiscovery = { projectId: string, roots: Array<WorkspaceRootDiscovery>, truncated: boolean, scannedAtMs: number, };
