// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceGitStatus } from "./WorkspaceGitStatus";
import type { WorkspaceScanStats } from "./WorkspaceScanStats";
import type { WorkspaceScript } from "./WorkspaceScript";
import type { WorkspaceSourceEntry } from "./WorkspaceSourceEntry";
import type { WorkspaceTechEntry } from "./WorkspaceTechEntry";

export type WorkspaceRootDiscovery = {
/**
 * Canonicalized root path from the binding record.
 */
rootPath: string, packageName: string | null,
/**
 * "pnpm" | "yarn" | "npm" | "bun" from lockfile priority.
 */
packageManager: string | null, techStack: Array<WorkspaceTechEntry>, scripts: Array<WorkspaceScript>, sources: Array<WorkspaceSourceEntry>, git: WorkspaceGitStatus, stats: WorkspaceScanStats,
/**
 * Per-root diagnosable problems; remaining roots still scan.
 */
errors: Array<string>, truncated: boolean, };
