// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceGitDiff } from "./WorkspaceGitDiff";

/**
 * Whole-repo diff for one bound root (E3 cross-root aggregation).
 */
export type WorkspaceRootGitDiff = { rootIndex: number, git: WorkspaceGitDiff, };
