// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceGitDiff = { repoRoot: string | null,
/**
 * False when the git binary is unavailable, errors, or times out.
 */
available: boolean, error: string | null,
/**
 * `git diff HEAD` output, extended with `/dev/null -> new file` diffs
 * for untracked files (capped per request; excess is reported in a
 * trailing `# N untracked files omitted` line). Ignored files stay out.
 */
unifiedDiff: string | null, };
