// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceFileEvent } from "./WorkspaceFileEvent";

/**
 * Broadcast to all connections; one per debounce window per project.
 */
export type WorkspaceChangedNotification = { projectId: string,
/**
 * Capped at MAX_WATCH_EVENTS_PER_NOTIFICATION; see `overflow`.
 */
changes: Array<WorkspaceFileEvent>,
/**
 * True when the debounce window held more events than the cap.
 */
overflow: boolean,
/**
 * Pending changesets whose base hashes were contradicted by this
 * event batch; clients should prompt re-index/re-create.
 */
invalidatedChangesets?: Array<string>, };
