// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceValidationKind } from "./WorkspaceValidationKind";

export type WorkspaceValidationCheck = { kind: WorkspaceValidationKind,
/**
 * Script name from the root's package.json (E0 scan `scripts`).
 * The runtime does not guess script mappings (narrow protocol).
 */
script: string,
/**
 * Root to run the check in; None = primary root (E1 behavior).
 */
rootIndex?: number, };
