// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSourceRange = {
/**
 * 1-based inclusive start line of the symbol block.
 */
startLine: number,
/**
 * 1-based inclusive end line of the symbol block.
 */
endLine: number, };
