// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSourceArtifact } from "./WorkspaceSourceArtifact";
import type { WorkspaceSourceRef } from "./WorkspaceSourceRef";

export type WorkspaceSourceResolveMatch = { artifact: WorkspaceSourceArtifact, sourceRef: WorkspaceSourceRef, };
