// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceChangeSetCheckpoint } from "./WorkspaceChangeSetCheckpoint";
import type { WorkspaceChangeSetStatus } from "./WorkspaceChangeSetStatus";
import type { WorkspaceFileChange } from "./WorkspaceFileChange";

export type WorkspaceChangeSet = {
/**
 * Server-generated `cs-{uuid}`.
 */
id: string, projectId: string, title: string, schemaVersion: number, changes: Array<WorkspaceFileChange>, status: WorkspaceChangeSetStatus, checkpoint: WorkspaceChangeSetCheckpoint,
/**
 * Unified diff (base -> proposed) computed at create time.
 */
unifiedDiff: string, createdAtMs: number, updatedAtMs: number, appliedAtMs: number,
/**
 * E4: set when an external edit invalidated one or more base hashes
 * while the changeset was Pending. Presence blocks apply with a
 * structured conflict error. `None` = healthy.
 */
invalidatedReason?: string, };
