// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserControlMode } from "./BrowserControlMode";
import type { ViewportConfig } from "./ViewportConfig";

/**
 * Configuration for the browser control layer.
 */
export type BrowserControlConfig = { 
/**
 * Local launch or external debug connection.
 */
mode: BrowserControlMode, 
/**
 * Explicit path to the Chrome/Chromium executable.
 * When omitted, the process-lifecycle layer discovers it.
 */
chrome_executable: string | null, 
/**
 * Run Chrome in headless mode.
 */
headless: boolean, 
/**
 * Viewport used when launching the browser.
 */
viewport: ViewportConfig, 
/**
 * Run Chrome with the OS sandbox enabled.
 */
sandbox: boolean, 
/**
 * Disable browser extensions and prevent loading them.
 */
disable_extensions: boolean, 
/**
 * Additional arguments passed to Chrome on launch.
 * Dangerous arguments are filtered by [`BrowserControlConfig::sanitize_args`].
 */
extra_args: Array<string>, 
/**
 * Maximum number of concurrent Chrome processes across the whole process.
 */
max_concurrent_browsers: number, 
/**
 * Maximum time to wait for a browser concurrency permit before failing.
 */
browser_permit_acquire_timeout_ms: bigint, 
/**
 * Default timeout for CDP commands, in milliseconds.
 */
command_timeout_ms: bigint, 
/**
 * Navigation timeout, in milliseconds.
 */
navigation_timeout_ms: bigint, 
/**
 * Timeout for launching a local Chrome process, in milliseconds.
 */
launch_timeout_ms: bigint, 
/**
 * WebSocket connection timeout for external browsers, in milliseconds.
 */
connect_timeout_ms: bigint, 
/**
 * External browser debug WebSocket URL (used when `mode == External`).
 */
connect_url: string | null, 
/**
 * Whether to allow navigation to local/private network targets.
 */
allow_local_network: boolean, 
/**
 * In external mode, whether to allow sensitive operations (click, type, evaluate).
 */
external_browser_allow_sensitive: boolean, 
/**
 * Maximum size of a single console message stored in the event buffer.
 */
max_console_message_bytes: number, 
/**
 * Maximum number of entries retained in the event buffer.
 */
max_event_entries: number, 
/**
 * Maximum total bytes retained in the event buffer.
 */
max_event_buffer_bytes: number, };
