// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Viewport configuration passed to Chrome on launch.
 */
export type ViewportConfig = { 
/**
 * Viewport width in CSS pixels.
 */
width: number, 
/**
 * Viewport height in CSS pixels.
 */
height: number, 
/**
 * Optional device scale factor (e.g. 2.0 for retina-like emulation).
 */
device_scale_factor: number | null, };
