// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null,
/**
 * Context size at which auto-compaction triggers, when one applies. This
 * is what a "context left" indicator counts down to; see
 * `ody_protocol::protocol::TokenUsageInfo::auto_compact_token_limit`.
 */
autoCompactTokenLimit: number | null, };
